#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

unexport MAKEFILE_LIST
override PKGDIR = configPkg
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/tools/configuro/template/linker.cmd.asm.xdt:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/tools/configuro/template/linker.cmd.asm.xdt
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/xmlgen2.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/xmlgen2.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/package.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/package.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/xmlgen.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/xmlgen.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/ti/targets/ITarget.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/ti/targets/ITarget.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/services/io/package.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/services/io/package.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/Repository.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/Repository.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/om2.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/om2.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/BuildEnvironment.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/BuildEnvironment.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/PackageContents.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/PackageContents.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/Script.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/Script.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/tools/configuro/template/compiler.opt.xdt:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/tools/configuro/template/compiler.opt.xdt
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/ITarget.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/ITarget.xs
package.mak: config.bld
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/ti/targets/package.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/ti/targets/package.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/services/global/Clock.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/services/global/Clock.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/Executable.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/Executable.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/services/global/Trace.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/services/global/Trace.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/ti/targets/arm/package.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/ti/targets/arm/package.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/Utils.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/Utils.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/xdc.tci:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/xdc.tci
package.mak: package.bld
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/tools/configuro/template/custom.mak.asm.xdt:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/tools/configuro/template/custom.mak.asm.xdt
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/bld.js:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/bld.js
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/template.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/template.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/Manifest.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/Manifest.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/tools/configuro/template/package.xs.xdt:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/tools/configuro/template/package.xs.xdt
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/_gen.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/_gen.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/include/utils.tci:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/include/utils.tci
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/ITargetFilter.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/ITargetFilter.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/package.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/package.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/services/io/File.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/services/io/File.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/IPackage.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/IPackage.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/Library.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/Library.xs
endif

ti.targets.arm.Arm11_big_endian.rootDir ?= C:/PROGRA~1/TEXASI~1/ccsv4/tools/compiler/tms470
ti.targets.arm.packageBase ?= C:/Program Files/Texas Instruments/xdctools_3_20_03_63/packages/ti/targets/arm/
.PRECIOUS: $(XDCCFGDIR)/%.o11e
.PHONY: all,11e .dlls,11e .executables,11e test,11e
all,11e: .executables,11e
.executables,11e: .libraries,11e
.executables,11e: .dlls,11e
.dlls,11e: .libraries,11e
.libraries,11e: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,11e
	@$(ECHO) xdc .executables,11e
	@$(ECHO) xdc .libraries,11e
	@$(ECHO) xdc .dlls,11e


all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.inc package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.inc package/%_configPkg.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package configPkg" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs $(MK_IDLOPTS) -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

.dlls,11e .dlls: mutex.p11e

-include package/cfg/mutex_p11e.mak
ifneq (clean,$(MAKECMDGOALS))
-include package/cfg/mutex_p11e.dep
endif
package/cfg/mutex_p11e.o11e : | package/cfg/mutex_p11e.xdl
mutex.p11e:
	$(RM) $@
	@$(MSG) lnk11e $@ ...
	$(RM) $(XDCCFGDIR)/$@.map
	$(ti.targets.arm.Arm11_big_endian.rootDir)/bin/lnk470  --opt='-mv6 --abi=ti_arm9_abi -qq -pdsw225  --diag_suppress=23000 -oe  -ms -op2 -O3 -k -os --inline_recursion_limit=20'  -q -o $@ package/cfg/mutex_p11e.o11e  package/cfg/mutex_p11e.xdl --silicon_version=6 --strict_compatibility=on -r -m $(XDCCFGDIR)/$@.map
	-$(MV) $(notdir $(basename $@)).asm $(XDCCFGDIR)$(dir $@)/lto_$(notdir $(basename $@)).opt11e
	$(MV) $@ $(XDCCFGDIR)/$@.obj
	$(TOUCH) $@
	$(MV) $(XDCCFGDIR)$@.obj $(XDCCFGDIR)$@.pobj
	$(SED) -r 's/sect[ 	]"[[0-9]+]/sect      "/g' <$(XDCCFGDIR)$(dir $@)/lto_$(notdir $(basename $@)).opt11e>$(XDCCFGDIR)$@.s11e
	$(ti.targets.arm.Arm11_big_endian.rootDir)/bin/cl470 -c -qq -mv6 --abi=ti_arm9_abi -eo.obj -ea.s11e     $(XDCINCS) -I$(ti.targets.arm.Arm11_big_endian.rootDir)/include/rts -I$(ti.targets.arm.Arm11_big_endian.rootDir)/include  -fr=./$(XDCCFGDIR) -fa $(XDCCFGDIR)$@.s11e
mutex.p11e:C_DIR=
mutex.p11e: PATH:=$(ti.targets.arm.Arm11_big_endian.rootDir)/bin/;$(PATH)
mutex.p11e: Path:=$(ti.targets.arm.Arm11_big_endian.rootDir)/bin/;$(PATH)


ifeq (,$(wildcard .libraries,11e))
mutex.p11e package/cfg/mutex_p11e.c: .libraries,11e
endif

package/cfg/mutex_p11e.c package/cfg/mutex_p11e.h package/cfg/mutex_p11e.xdl: override _PROG_NAME := mutex.p11e
package/cfg/mutex_p11e.c: package/cfg/mutex_p11e.cfg

clean:: clean,11e
	-$(RM) package/cfg/mutex_p11e.cfg
	-$(RM) package/cfg/mutex_p11e.dep
	-$(RM) package/cfg/mutex_p11e.c
	-$(RM) package/cfg/mutex_p11e.xdc.inc

clean,11e::
	-$(RM) mutex.p11e
	-$(RM) .tmp,mutex.p11e,*

clean:: 
	-$(RM) package/cfg/mutex_p11e.pjt
%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@
mutex_p11e.s11e,copy : package/cfg/mutex_p11e.s11e
mutex_p11e.o11e,copy : package/cfg/mutex_p11e.o11e

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg .interfaces $(XDCROOT)/packages/xdc/cfg/Main.xs
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_XSOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,configPkg
configPkg.tar: package/build.cfg
configPkg.tar: package/package.ext.xml
configPkg.tar: package/package.xdc.inc
configPkg.tar: package/package.bld.xml
configPkg.tar: package/package.rel.dot
ifneq (clean,$(MAKECMDGOALS))
-include package/rel/configPkg.tar.dep
endif
package/rel/configPkg/configPkg/package/package.rel.xml:

configPkg.tar: package/rel/configPkg.xdc.inc package/rel/configPkg/configPkg/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELTAR,package/rel/configPkg.xdc.inc,package/rel/configPkg.tar.dep)


release release,configPkg: all configPkg.tar
clean:: .clean
	-$(RM) configPkg.tar
	-$(RM) package/rel/configPkg.xdc.inc
	-$(RM) package/rel/configPkg.tar.dep

clean:: .clean
	-$(RM) .libraries .libraries,*
clean:: 
	-$(RM) .dlls .dlls,*
#
# The following clean rule removes user specified
# generated files or directories.
#

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/external))
    $(shell $(MKDIR) package/external)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
endif
clean::
	-$(RMDIR) package

include custom.mak
clean:: 
	-$(RM) package/configPkg.pjt
