#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

unexport MAKEFILE_LIST
override PKGDIR = configPkg
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/services/global/Trace.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/services/global/Trace.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/_gen.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/_gen.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/tools/configuro/template/linker.cmd.asm.xdt:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/tools/configuro/template/linker.cmd.asm.xdt
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/tools/configuro/template/package.xs.xdt:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/tools/configuro/template/package.xs.xdt
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/tools/configuro/template/compiler.opt.xdt:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/tools/configuro/template/compiler.opt.xdt
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/Executable.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/Executable.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/template.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/template.xs
package.mak: package.bld
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/services/io/File.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/services/io/File.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/ti/targets/arm/package.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/ti/targets/arm/package.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/Library.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/Library.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/xmlgen2.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/xmlgen2.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/Repository.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/Repository.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/ITarget.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/ITarget.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/package.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/package.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/PackageContents.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/PackageContents.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/Manifest.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/Manifest.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/xmlgen.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/xmlgen.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/Script.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/Script.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/BuildEnvironment.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/BuildEnvironment.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/tools/configuro/template/custom.mak.asm.xdt:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/tools/configuro/template/custom.mak.asm.xdt
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/om2.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/om2.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/services/global/Clock.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/services/global/Clock.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/ti/targets/arm/elf/IArm.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/ti/targets/arm/elf/IArm.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/xdc.tci:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/xdc.tci
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/IPackage.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/IPackage.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/ITargetFilter.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/ITargetFilter.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/services/io/package.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/services/io/package.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/ti/targets/arm/elf/package.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/ti/targets/arm/elf/package.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/include/utils.tci:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/include/utils.tci
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/bld.js:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/bld.js
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/ti/targets/package.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/ti/targets/package.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/ti/targets/ITarget.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/ti/targets/ITarget.xs
package.mak: config.bld
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/Utils.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/Utils.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/package.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/package.xs
endif

ti.targets.arm.elf.Arm9.rootDir ?= C:/PROGRA~1/TEXASI~1/ccsv4/tools/compiler/tms470
ti.targets.arm.elf.packageBase ?= C:/Program Files/Texas Instruments/xdctools_3_20_03_63/packages/ti/targets/arm/elf/
.PRECIOUS: $(XDCCFGDIR)/%.oe9
.PHONY: all,e9 .dlls,e9 .executables,e9 test,e9
all,e9: .executables,e9
.executables,e9: .libraries,e9
.executables,e9: .dlls,e9
.dlls,e9: .libraries,e9
.libraries,e9: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,e9
	@$(ECHO) xdc .executables,e9
	@$(ECHO) xdc .libraries,e9
	@$(ECHO) xdc .dlls,e9


all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.inc package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.inc package/%_configPkg.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package configPkg" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs $(MK_IDLOPTS) -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

.dlls,e9 .dlls: mutex.pe9

-include package/cfg/mutex_pe9.mak
ifneq (clean,$(MAKECMDGOALS))
-include package/cfg/mutex_pe9.dep
endif
package/cfg/mutex_pe9.oe9 : | package/cfg/mutex_pe9.xdl
mutex.pe9:
	$(RM) $@
	@$(MSG) lnke9 $@ ...
	$(RM) $(XDCCFGDIR)/$@.map
	$(ti.targets.arm.elf.Arm9.rootDir)/bin/lnk470  --opt='-me -mv5e --abi=eabi -qq -pdsw225  --diag_suppress=23000 -oe  -ms -op2 -O3 -k -os --inline_recursion_limit=20'  -q -o $@ package/cfg/mutex_pe9.oe9  package/cfg/mutex_pe9.xdl --silicon_version=5e --strict_compatibility=on -r -m $(XDCCFGDIR)/$@.map
	-$(MV) $(notdir $(basename $@)).asm $(XDCCFGDIR)$(dir $@)/lto_$(notdir $(basename $@)).opte9
	$(MV) $@ $(XDCCFGDIR)/$@.obj
	$(TOUCH) $@
	$(MV) $(XDCCFGDIR)$@.obj $(XDCCFGDIR)$@.pobj
	$(SED) -r 's/sect[ 	]"[[0-9]+]/sect      "/g' <$(XDCCFGDIR)$(dir $@)/lto_$(notdir $(basename $@)).opte9>$(XDCCFGDIR)$@.se9
	$(ti.targets.arm.elf.Arm9.rootDir)/bin/cl470 -c -qq -me -mv5e --abi=eabi -eo.obj -ea.se9     $(XDCINCS) -I$(ti.targets.arm.elf.Arm9.rootDir)/include/rts -I$(ti.targets.arm.elf.Arm9.rootDir)/include  -fr=./$(XDCCFGDIR) -fa $(XDCCFGDIR)$@.se9
mutex.pe9:C_DIR=
mutex.pe9: PATH:=$(ti.targets.arm.elf.Arm9.rootDir)/bin/;$(PATH)
mutex.pe9: Path:=$(ti.targets.arm.elf.Arm9.rootDir)/bin/;$(PATH)


ifeq (,$(wildcard .libraries,e9))
mutex.pe9 package/cfg/mutex_pe9.c: .libraries,e9
endif

package/cfg/mutex_pe9.c package/cfg/mutex_pe9.h package/cfg/mutex_pe9.xdl: override _PROG_NAME := mutex.pe9
package/cfg/mutex_pe9.c: package/cfg/mutex_pe9.cfg

clean:: clean,e9
	-$(RM) package/cfg/mutex_pe9.cfg
	-$(RM) package/cfg/mutex_pe9.dep
	-$(RM) package/cfg/mutex_pe9.c
	-$(RM) package/cfg/mutex_pe9.xdc.inc

clean,e9::
	-$(RM) mutex.pe9
	-$(RM) .tmp,mutex.pe9,*

clean:: 
	-$(RM) package/cfg/mutex_pe9.pjt
%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@
mutex_pe9.se9,copy : package/cfg/mutex_pe9.se9
mutex_pe9.oe9,copy : package/cfg/mutex_pe9.oe9

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg .interfaces $(XDCROOT)/packages/xdc/cfg/Main.xs
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_XSOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,configPkg
configPkg.tar: package/build.cfg
configPkg.tar: package/package.ext.xml
configPkg.tar: package/package.xdc.inc
configPkg.tar: package/package.bld.xml
configPkg.tar: package/package.rel.dot
ifneq (clean,$(MAKECMDGOALS))
-include package/rel/configPkg.tar.dep
endif
package/rel/configPkg/configPkg/package/package.rel.xml:

configPkg.tar: package/rel/configPkg.xdc.inc package/rel/configPkg/configPkg/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELTAR,package/rel/configPkg.xdc.inc,package/rel/configPkg.tar.dep)


release release,configPkg: all configPkg.tar
clean:: .clean
	-$(RM) configPkg.tar
	-$(RM) package/rel/configPkg.xdc.inc
	-$(RM) package/rel/configPkg.tar.dep

clean:: .clean
	-$(RM) .libraries .libraries,*
clean:: 
	-$(RM) .dlls .dlls,*
#
# The following clean rule removes user specified
# generated files or directories.
#

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/external))
    $(shell $(MKDIR) package/external)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
endif
clean::
	-$(RMDIR) package

include custom.mak
clean:: 
	-$(RM) package/configPkg.pjt
