#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

unexport MAKEFILE_LIST
override PKGDIR = configPkg
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/tools/configuro/template/linker.cmd.asm.xdt:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/tools/configuro/template/linker.cmd.asm.xdt
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/xmlgen2.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/xmlgen2.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/package.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/package.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/xmlgen.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/xmlgen.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/ti/targets/ITarget.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/ti/targets/ITarget.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/services/io/package.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/services/io/package.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/Repository.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/Repository.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/om2.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/om2.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/BuildEnvironment.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/BuildEnvironment.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/PackageContents.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/PackageContents.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/Script.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/Script.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/tools/configuro/template/compiler.opt.xdt:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/tools/configuro/template/compiler.opt.xdt
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/ITarget.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/ITarget.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/ti/targets/package.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/ti/targets/package.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/services/global/Clock.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/services/global/Clock.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/Executable.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/Executable.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/services/global/Trace.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/services/global/Trace.xs
package.mak: package.bld
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/Utils.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/Utils.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/xdc.tci:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/xdc.tci
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/tools/configuro/template/custom.mak.asm.xdt:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/tools/configuro/template/custom.mak.asm.xdt
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/bld.js:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/bld.js
package.mak: config.bld
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/template.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/template.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/Manifest.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/Manifest.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/tools/configuro/template/package.xs.xdt:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/tools/configuro/template/package.xs.xdt
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/_gen.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/_gen.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/include/utils.tci:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/include/utils.tci
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/ITargetFilter.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/ITargetFilter.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/package.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/package.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/services/io/File.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/services/io/File.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/IPackage.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/IPackage.xs
C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/Library.xs:
package.mak: C:/Program\ Files/Texas\ Instruments/xdctools_3_20_03_63/packages/xdc/bld/Library.xs
endif

ti.targets.C674.rootDir ?= C:/PROGRA~1/TEXASI~1/ccsv4/tools/compiler/c6000
ti.targets.packageBase ?= C:/Program Files/Texas Instruments/xdctools_3_20_03_63/packages/ti/targets/
.PRECIOUS: $(XDCCFGDIR)/%.o674
.PHONY: all,674 .dlls,674 .executables,674 test,674
all,674: .executables,674
.executables,674: .libraries,674
.executables,674: .dlls,674
.dlls,674: .libraries,674
.libraries,674: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,674
	@$(ECHO) xdc .executables,674
	@$(ECHO) xdc .libraries,674
	@$(ECHO) xdc .dlls,674


all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.inc package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.inc package/%_configPkg.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package configPkg" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs $(MK_IDLOPTS) -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

.dlls,674 .dlls: message_dsp.p674

-include package/cfg/message_dsp_p674.mak
ifneq (clean,$(MAKECMDGOALS))
-include package/cfg/message_dsp_p674.dep
endif
package/cfg/message_dsp_p674.o674 : | package/cfg/message_dsp_p674.xdl
message_dsp.p674:
	$(RM) $@
	@$(MSG) lnk674 $@ ...
	$(RM) $(XDCCFGDIR)/$@.map
	$(ti.targets.C674.rootDir)/bin/lnk6x  --opt='-mv6740 -qq -pdsw225  --diag_suppress=23000 -oe  -mo -op2 -O3 -k -os --no_compress --inline_recursion_limit=20'  -q -o $@ package/cfg/message_dsp_p674.o674  package/cfg/message_dsp_p674.xdl  -r -m $(XDCCFGDIR)/$@.map
	-$(MV) $(notdir $(basename $@)).asm $(XDCCFGDIR)$(dir $@)/lto_$(notdir $(basename $@)).opt674
	$(MV) $@ $(XDCCFGDIR)/$@.obj
	$(TOUCH) $@
	$(MV) $(XDCCFGDIR)$@.obj $(XDCCFGDIR)$@.pobj
	$(SED) -r 's/sect[ 	]"[[0-9]+]/sect      "/g' <$(XDCCFGDIR)$(dir $@)/lto_$(notdir $(basename $@)).opt674>$(XDCCFGDIR)$@.s674
	$(ti.targets.C674.rootDir)/bin/cl6x -c -qq -mv6740 -eo.obj -ea.s674     $(XDCINCS) -I$(ti.targets.C674.rootDir)/include -fr=./$(XDCCFGDIR) -fa $(XDCCFGDIR)$@.s674
message_dsp.p674:C_DIR=
message_dsp.p674: PATH:=$(ti.targets.C674.rootDir)/bin/;$(PATH)
message_dsp.p674: Path:=$(ti.targets.C674.rootDir)/bin/;$(PATH)


ifeq (,$(wildcard .libraries,674))
message_dsp.p674 package/cfg/message_dsp_p674.c: .libraries,674
endif

package/cfg/message_dsp_p674.c package/cfg/message_dsp_p674.h package/cfg/message_dsp_p674.xdl: override _PROG_NAME := message_dsp.p674
package/cfg/message_dsp_p674.c: package/cfg/message_dsp_p674.cfg

clean:: clean,674
	-$(RM) package/cfg/message_dsp_p674.cfg
	-$(RM) package/cfg/message_dsp_p674.dep
	-$(RM) package/cfg/message_dsp_p674.c
	-$(RM) package/cfg/message_dsp_p674.xdc.inc

clean,674::
	-$(RM) message_dsp.p674
	-$(RM) .tmp,message_dsp.p674,*

clean:: 
	-$(RM) package/cfg/message_dsp_p674.pjt
%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@
message_dsp_p674.s674,copy : package/cfg/message_dsp_p674.s674
message_dsp_p674.o674,copy : package/cfg/message_dsp_p674.o674

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg .interfaces $(XDCROOT)/packages/xdc/cfg/Main.xs
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_XSOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,configPkg
configPkg.tar: package/build.cfg
configPkg.tar: package/package.ext.xml
configPkg.tar: package/package.xdc.inc
configPkg.tar: package/package.bld.xml
configPkg.tar: package/package.rel.dot
ifneq (clean,$(MAKECMDGOALS))
-include package/rel/configPkg.tar.dep
endif
package/rel/configPkg/configPkg/package/package.rel.xml:

configPkg.tar: package/rel/configPkg.xdc.inc package/rel/configPkg/configPkg/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELTAR,package/rel/configPkg.xdc.inc,package/rel/configPkg.tar.dep)


release release,configPkg: all configPkg.tar
clean:: .clean
	-$(RM) configPkg.tar
	-$(RM) package/rel/configPkg.xdc.inc
	-$(RM) package/rel/configPkg.tar.dep

clean:: .clean
	-$(RM) .libraries .libraries,*
clean:: 
	-$(RM) .dlls .dlls,*
#
# The following clean rule removes user specified
# generated files or directories.
#

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/external))
    $(shell $(MKDIR) package/external)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
endif
clean::
	-$(RMDIR) package

include custom.mak
clean:: 
	-$(RM) package/configPkg.pjt
